Feat/modal
Tinkerbell-Green/need-compliments pull request #3
Opened 2022-03-02 14:09 UTC by hotbreakb

## 어려웠던 점
1. `styled.css`에서 이름 정하기
2. 모달 바깥 영역을 클릭했을 때 모달 사라지는 기능 구현하기
3. 정확한 디자인 시안이 없이 구현하기

## 동작 영상
코드를 이해하시는 데 도움이 될 거 같아 영상을 찍어봤습니다 :) 모달 바깥쪽을 누르면 모달이 꺼지고, 모달 안쪽을 누르면 유지되는 모습입니다. 더 필요한 동작이 있으면 알려주세요!
<video src="https://user-images.githubusercontent.com/64337152/156377332-f7526cca-7047-4e78-8869-0ed6343e3e2f.mov">

2022-03-02 14:11 UTC, hotbreakb commented
음... 근데 왜 재현님께서 하신 커밋이 그대로 남아있을까요? 제가 브랜치 받을 때 `developer`에서 끌고 왔는데 거기서 커밋되었던 내역이 그대로 가져와지는 걸까요?

2022-03-02 14:14 UTC, ghtea commented
현재 feat/modal -> master 로 PR  요청하셔서 그래요.
feat/modal -> develop 으로 수정해주시면 될거 같아요!
(master 는 공식 배포 버전 느낌)

2022-03-02 14:18 UTC, hotbreakb commented
developer로 변경했습니다! 왜 저렇게 된 건지 바로 알아차리는 모습이 너무 멋지네요🤭

2022-03-03 03:51 UTC, ghtea requested changes
수고하셨어요!!

참고로 modal test 하려고 만든 페이지가 있었다면 다음부턴 삭제 안하고 PR 요청해도 될거 같아요.
지금은 modal 쓰이는 곳이 없으니 테스트할 페이지 필요하긴 할거 같아서요

2022-03-03 03:51 UTC, ghtea commented on .env
> +NEXT_PUBLIC_NAVER_CLIENT_ID = 0Rb1S5HtC0aOGRSdNLDe
.env 가 올라왔네요
저도 똑같은 실수를 했는데
Next js 기본 템플렛 에서 .env  가 아닌 .env.local 을 gitignore 에 넣어줬네요

1. .env 지우고 나서 push
2. .env.local 생성하고 같은 코드 넣어서 push

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.styled.ts
> +export const StyledUl = styled.ul`
컴포넌트 파일에서 S로 impot해서 S.StyledUl 처럼 이용하잖아요?
그 이유중 하나가,  Styled 의 약자 S 로 해서 styled component 임을 알려주기 위해서에요.
그래서 StyledUl 처럼 Styled 를 또 붙여줄 필요는 없는거 같아요

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.styled.ts
> +export const StyledUl = styled.ul`
저라면 ActionList 혹은 ActionsContainer 등 처럼 지을거 같아요

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.styled.ts
> +export const StyledLi = styled.li`
이건 아마 ActionContainer ?

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.styled.ts
> +export const OutsideModal = styled.section`
OutsideModal 도 큰문제가 없는데,
Modal 뒤에도 있는 영역이니 저라면 Background 로 할거 같아요!

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.tsx
> +  const [isModalOpen, setModalOpen] = useState<boolean>(true);
```suggestion
  const [isModalOpen, setIsModalOpen] = useState(true);
```
기본값으로 true 혹은 false 를 넣으면 자동으로 <boolean>으로 됩니다!

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.tsx
> +  const onModalOff = (e: React.MouseEvent<HTMLElement, MouseEvent>) => {
1. onOutsideClick 등 뭘 클릭했는지 나타내는게 파악하기 편할거 같아요.
2. e: ... 처럼 파라미터에 타입을 지정해도 되지만, onModalOff: React.MouseEventHandler<HTMLElement> 처럼 해도돼요. 상황에 맞게 선택해서 이용하면 될거 같아요 (지금은 큰 차이 없어 보임)

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.tsx
> +          onClick={(e: React.MouseEvent<HTMLElement, MouseEvent>) => {
onClick={onModalOff} 로 하시면 돼요!

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.tsx
> +    const clicked: Element | null = (e.target! as Element).closest(".modal");
isModalClicked 로 하면 파악하기 쉬울거 같아요

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.tsx
> +    const clicked: Element | null = (e.target! as Element).closest(".modal");
closest 처음보는데 덕분에 배워가요 👍

2022-03-03 03:51 UTC, ghtea commented on components/modal/modal.tsx
> +    const clicked: Element | null = (e.target! as Element).closest(".modal");
좀 다듬으면
```
const isModalClicked = (e.target instanceof Element) && e.target.closest(".modal") !== null

    if (isModalClicked) return;
```

2022-03-03 04:13 UTC, hotbreakb commented on components/modal/modal.tsx
> +  const onModalOff = (e: React.MouseEvent<HTMLElement, MouseEvent>) => {
`onModalOff: React.MouseEventHandler` 이렇게 하면 return 타입을 적는 거니까 e에 input 타입을 적는 것과 다른 의미 아닌가요?

2022-03-03 04:25 UTC, ghtea commented on components/modal/modal.tsx
> +  const onModalOff = (e: React.MouseEvent<HTMLElement, MouseEvent>) => {
`onModalOff: React.MouseEventHandler` 이렇게 하면 함수 타입을 지정하는 거에요.
const onModalOff = (e: React.MouseEvent<HTMLElement, MouseEvent>): `여기` 에 타입지정하면 리턴 타입지정하는거고요!

2022-03-03 04:29 UTC, hotbreakb commented
### 재현님 리뷰 정리
1. .env 올린 거 삭제
2. styled를 S로 쓰니까 S로 시작하지 않는 다른 의미있는 단어 사용
3. `useState(true of false)`로 하면 `<boolean>`으로 된다. (저는 명시적으로 드러내는 게 좋아서 그냥 두겠습니다!)
4. on/off 보다는 어떤 동작이 되는 것인지 드러내기

2022-03-03 06:38 UTC, hotbreakb commented on components/modal/modal.tsx
> +  const onModalOff = (e: React.MouseEvent<HTMLElement, MouseEvent>) => {
왜 이렇게 해도 되는 건지 궁금해서 찾아봤더니 재현님께서 말씀해주신 것처럼 하면 input type이 MouseEvent<T>로 지정돼서 그런 거였군요. 감사합니다!
`type MouseEventHandler<T = Element> = EventHandler<MouseEvent<T>>;`

2022-03-03 06:38 UTC, Hong-been reviewed
👍🏻👍🏻👍🏻👍🏻

2022-03-03 06:39 UTC, merged

2022-03-03 08:58 UTC, ghtea commented on components/modal/modal.tsx
> +  const [isModalOpenBtnClick, setModalOpenBtnClick] = useState<boolean>(true);
`isModalOpen, setIsModalOpen` 이요!

2022-03-03 09:04 UTC, ghtea commented on components/modal/modal.styled.ts
> +export const ActionList = styled.li`
좀 지치시겠지만 한번 익히면 습관이 되니 다시 알려드릴게요~

list 는 뭔가를 여러개 갖고있는 것 (<ul>: The Unordered List)
list item 은 list 의 각각의 항목 (<li>: The List Item element)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li

ActionContainer 안에 ActionList 가 아니라
ActionList (혹은 ActionsContainer) 안에 Action (ActionContainer, ActionListItem ) 에요!